### ISSUE TITLE
Issue configuring Bitbucket Branch Source Plugin

### ISSUE THREAD

**Issue by ericfrancis** [amuniz/bitbucket-branch-source-plugin#10]
Duplicate SO Question: https://stackoverflow.com/questions/44029404/issue-configuring-bitbucket-branch-source-plugin

I've configured the plugin with scanning credentials.

Found branches with a Jenkinsfile.

However, I'm getting the error below and am not sure how to proceed.

```
[Bitbucket] Notifying commit build result
[Bitbucket] Notifying commit build result
ERROR: Could not send notifications
com.cloudbees.jenkins.plugins.bitbucket.api.BitbucketRequestException: HTTP request error. Status: 400: Bad Request.
{"type": "error", "error": {"fields": {"url": ["Enter a valid URL."]}, "message": "Bad request"}}
jenkins bitbucket jenkins-plugins jenkins-pipeline
```

**Comment by spotlesscoder** [comment]
Is the error from the job output or the jenkins.err.log?

**Comment by spotlesscoder** [comment]
Maybe it is a proxy related issue. In my jenkins.err.log, I found the following strange behaviour:

(Masked <IP>:<PORT> and organizationname)

```
Jun 26, 2017 3:04:57 PM org.apache.commons.httpclient.HttpMethodDirector authenticateProxy
WARNING: Required proxy credentials not available for BASIC <any realm>@<IP>:<PORT>
Jun 26, 2017 3:04:57 PM org.apache.commons.httpclient.HttpMethodDirector authenticateProxy
WARNING: Preemptive authentication requested but no default proxy credentials available
Jun 26, 2017 3:04:57 PM org.apache.commons.httpclient.HttpMethodBase readResponseBody
INFO: Response content length is not known
Jun 26, 2017 3:04:58 PM org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$ConnectionPool freeConnection
SEVERE: Host connection pool not found, hostConfig=HostConfiguration[host=https://bitbucket.org, proxyHost=http://<IP>:<PORT>]
Jun 26, 2017 3:04:58 PM org.apache.commons.httpclient.HttpMethodDirector authenticateProxy
WARNING: Required proxy credentials not available for BASIC <any realm>@<IP>:<PORT>
Jun 26, 2017 3:04:58 PM org.apache.commons.httpclient.HttpMethodDirector authenticateProxy
WARNING: Preemptive authentication requested but no default proxy credentials available
Jun 26, 2017 3:04:58 PM org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$ConnectionPool freeConnection
SEVERE: Host connection pool not found, hostConfig=HostConfiguration[host=https://bitbucket.org, proxyHost=http://<IP>:<PORT>]
Jun 26, 2017 3:04:58 PM org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$ConnectionPool freeConnection
SEVERE: Host connection pool not found, hostConfig=HostConfiguration[host=https://bitbucket.org, proxyHost=http://<IP>:<PORT>]
Jun 26, 2017 3:04:58 PM com.cloudbees.jenkins.plugins.bitbucket.hooks.WebhookAutoRegisterListener registerHooks
INFO: Registering hook for organizationname/csdummyproject
Jun 26, 2017 3:04:58 PM org.apache.commons.httpclient.HttpMethodDirector authenticateProxy
WARNING: Required proxy credentials not available for BASIC <any realm>@<IP>:<PORT>
Jun 26, 2017 3:04:58 PM org.apache.commons.httpclient.HttpMethodDirector authenticateProxy
WARNING: Preemptive authentication requested but no default proxy credentials available
Jun 26, 2017 3:04:58 PM org.apache.commons.httpclient.HttpMethodBase readResponseBody
INFO: Response content length is not known
Jun 26, 2017 3:04:58 PM org.apache.commons.httpclient.HttpMethodBase readResponseBody
INFO: Response content length is not known
Jun 26, 2017 3:04:58 PM org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$ConnectionPool freeConnection
SEVERE: Host connection pool not found, hostConfig=HostConfiguration[host=https://bitbucket.org, proxyHost=http://<IP>:<PORT>]
Jun 26, 2017 3:04:58 PM jenkins.branch.MultiBranchProject$BranchIndexing run
INFO: playground/organizationname2/csdummyproject #20170626.150455 branch indexing action completed: SUCCESS in 2.5 sec
Jun 26, 2017 3:04:58 PM org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$ConnectionPool freeConnection
SEVERE: Host connection pool not found, hostConfig=HostConfiguration[host=https://bitbucket.org, proxyHost=http://<IP>:<PORT>]
Jun 26, 2017 3:04:58 PM com.cloudbees.jenkins.plugins.bitbucket.hooks.WebhookAutoRegisterListener$1 doRun
WARNING: Could not register hooks for playground/organizationname2/csdummyproject
com.cloudbees.jenkins.plugins.bitbucket.api.BitbucketRequestException: HTTP request error. Status: 400: Bad Request.
{"type": "error", "error": {"fields": {"url": ["Invalid URL"]}, "message": "Bad request"}}
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.postRequest(BitbucketCloudApiClient.java:636)
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.postRequest(BitbucketCloudApiClient.java:661)
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.registerCommitWebHook(BitbucketCloudApiClient.java:352)
	at com.cloudbees.jenkins.plugins.bitbucket.hooks.WebhookAutoRegisterListener.registerHooks(WebhookAutoRegisterListener.java:155)
	at com.cloudbees.jenkins.plugins.bitbucket.hooks.WebhookAutoRegisterListener.access$000(WebhookAutoRegisterListener.java:60)
	at com.cloudbees.jenkins.plugins.bitbucket.hooks.WebhookAutoRegisterListener$1.doRun(WebhookAutoRegisterListener.java:106)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

Howeever, using the GitHub Jenkins plugins for scanning an organization and building it's repos works very well on the same machine

**Comment by mariotacke** [comment]
@ericfrancis Did you ever figure out how to solve your problem? Running into the same thing right now.

```
Jenkins ver. 2.60.3
Bitbucket Branch Source Plugin: 2.2.7
Bitbucket Build Status Notifier Plugin: 1.3.3
```

**Comment by MaisUmGajo** [comment]
I have the same problem. Is there a solution ?

**Comment by kganger** [comment]
Having the same problem

**Comment by aferrandini** [comment]
Same problem here

**Comment by aferrandini** [comment]
@amuniz can we help?

**Comment by sysunix** [comment]
Having the same problem 
a  response?
