### ISSUE TITLE
branch source plugin shortens git repo location

### ISSUE THREAD

**Issue by Kollerb04** [amuniz/bitbucket-branch-source-plugin#9]
Occurs in 2.1.1 and 2.1.0. My first post so forgive me if it landed in the wrong place.
Bitbucket base url is http://something/bitbucket/. The team job is created, branches and repos are indexed properly. But all builds fail with trying to adress the repo with http://something/scm/someuser/repo.git while it should start with http://something/bitbucket/... ?

ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from http://something/scm/someuser/repo.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:806)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1070)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1101)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:109)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:130)
	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:107)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:232)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --progress http://something/scm/someuser/repo.git +refs/heads/master" returned status code 128:
stdout: 
stderr: fatal: repository 'http://something/scm/someuser/repo.git' not found

Jenkins ver 2.36 all plugins are up to date
https://issues.jenkins-ci.org/browse/JENKINS-42190

**Comment by fluky** [comment]
+1

**Comment by eloo** [comment]
same here :/

**Comment by spotlesscoder** [comment]
For me, it is similar. It takes forever at the step 

git fetch --tags --progress http://something/scm/someuser/repo.git +refs/heads/master

(Masked <IP>:<PORT> and organizationname)

![image](https://user-images.githubusercontent.com/25173078/27541813-965fec0e-5a85-11e7-946b-0fb2818a3e53.png)

**Comment by spotlesscoder** [comment]
Ok, the error might be a different one:

The final result of the Job is the following:

![image](https://user-images.githubusercontent.com/25173078/27542228-ec1baf7e-5a86-11e7-8769-67a24aa724ef.png)
